global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api_gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:3000"]

  - job_name: "auth_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:3001"]

  - job_name: "user_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:3002"]

  - job_name: "product_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:3003"]

  - job_name: "order_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:3004"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]